suggestions = {
    "dining-room":{ "Slug": "dining-room", "Name": "Dining Room", "Type": "Room" },
    "miss-scarlet":{ "Slug": "miss-scarlet", "Name": "Miss Scarlet", "Type": "Suspect" },
    "knife":{ "Slug": "knife", "Name": "Knife", "Type": "Weapon" },
    "kitchen":{ "Slug": "kitchen", "Name": "Kitchen", "Type": "Room" },
    "wrench":{ "Slug": "wrench", "Name": "Wrench", "Type": "Weapon" },
    "mrs-peacock":{ "Slug": "mrs-peacock", "Name": "Mrs. Peacock", "Type": "Suspect" },
    "mr-green":{ "Slug": "mr-green", "Name": "Mr. Green", "Type": "Suspect" },
    "lead-pipe":{ "Slug": "lead-pipe", "Name": "Lead Pipe", "Type": "Weapon" },
    "revolver":{ "Slug": "revolver", "Name": "Revolver", "Type": "Weapon" },
    "colonel-mustard":{ "Slug": "colonel-mustard", "Name": "Colonel Mustard", "Type": "Suspect" },
    "mrs-white":{ "Slug": "mrs-white", "Name": "Mrs. White", "Type": "Suspect" },
    "rope":{ "Slug": "rope", "Name": "Rope", "Type": "Weapon" },
    "library":{ "Slug": "library", "Name": "Library", "Type": "Room" },
    "candlestick":{ "Slug": "candlestick", "Name": "Candlestick", "Type": "Weapon" },
    "lounge":{ "Slug": "lounge", "Name": "Lounge", "Type": "Room" },
    "billiard-room":{ "Slug": "billiard-room", "Name": "Billiard Room", "Type": "Room" },
    "hall":{ "Slug": "hall", "Name": "Hall", "Type": "Room" },
    "ballroom":{ "Slug": "ballroom", "Name": "Ballroom", "Type": "Room" },
    "study":{ "Slug": "study", "Name": "Study", "Type": "Room" },
    "conservatory":{ "Slug": "conservatory", "Name": "Conservatory", "Type": "Room" },
    "professor-plum":{ "Slug": "professor-plum", "Name": "Professor Plum", "Type": "Suspect" },

}
